services:
  api:
    container_name: node-server
    image: node-server
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    restart: unless-stopped
    stdin_open: true
    env_file: .env.development.local
    networks:
      - node-server
    ports:
      - "4000:4000"
    volumes:
      - .:/node-server
      - /node-server/node_modules

networks:
  node-server:
    name: node-server

