version: "3.9"

services:
  api:
    container_name: node-api
    image: node-api
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    restart: unless-stopped
    stdin_open: true
    env_file: .env
    networks:
      - mern-api-network
    ports:
      - "4000:4000"
    volumes:
      - .:/appdir
      - node_modules:/appdir/node_modules
networks:
  mern-api-network:
    name: mern-api-network

volumes:
  mongodb-cluster:
    driver: local
    name: mongodb-cluster
  node_modules:
    name: node-modules
