version: "3.9"

services:
  api:
    container_name: node-api
    image: node-api
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    restart: unless-stopped
    stdin_open: true
    env_file: .env
    networks:
      - node-api-net
    ports:
      - "4000:4000"
    volumes:
      - .:/appdir
      - node_modules:/appdir/node_modules
networks:
  node-api-net:
    name: node-api-net

volumes:
  node_modules:
    name: node-modules
